# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c41371feec62fdc9e7b1afec98fe503f46bebcac8da45384dfa966c4423d7c2063e1ba744375ee8e237b092cb122b276b627599780a84d30b2b944d04f478b

test:
  secret_key_base: 21a5907e67a3e738749b6a311cc00106e44c3dfd3e9fc98e1204d09c738eb7735f24b50da3bd18a5525b7d04a3a6d3884ca4a08d11f072d7be79cfea43adf859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
